# Generated by Django 3.2.9 on 2021-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='wage',
            field=models.IntegerField(default=0),
        ),
    ]
