# Generated by Django 3.2.9 on 2021-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.user')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
