# Generated by Django 3.2.9 on 2021-12-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
